---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pritamdas.dev.pritamdas.dev
  resources:
  - pritams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pritamdas.dev.pritamdas.dev
  resources:
  - pritams/finalizers
  verbs:
  - update
- apiGroups:
  - pritamdas.dev.pritamdas.dev
  resources:
  - pritams/status
  verbs:
  - get
  - patch
  - update
