apiVersion: pritamdas.dev.pritamdas.dev/v1alpha1
kind: Pritam
metadata:
  labels:
    app.kubernetes.io/name: pritam
    app.kubernetes.io/instance: pritam-sample
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-crd
  name: pritam-sample-2
spec:
  name:
  replicas: 1
  container:
    image: "pritam99/api-server:0.0.1"
    port: 8080
  service:
    serviceName: "my-service-2"
    serviceType: "ClusterIP"
    servicePort: 8080
    serviceNodePort:
